# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 219b24818a94ac29507daf6ccfaec43ed19b09a83e07acf45a91d87c8598ef478334700cb571269147e26797c524aec24439660a6cacf4f02ecc84d45ae034aa

test:
  secret_key_base: f934efb2ff22ec98ea92f54c2bb974720e28ecbef014a26f0b4502c5de959efe70aa2930a38adb6d6a1fb6514080c42c49e98e3767af262366f98e36200ce3b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
